<section class="mb-7 grid gap-3 sm:grid-cols-3" aria-label="TODOの状況">
    <?php foreach ([['すべてのTODO', $todoSummary['total'], '登録済みのタスク', 'bg-emerald-800 text-white'], ['未完了', $todoSummary['remaining'], '次に取り組むタスク', 'border border-stone-200 bg-white/85 text-slate-900'], ['完了', $todoSummary['completed'], '片付いたタスク', 'border border-stone-200 bg-white/85 text-slate-900']] as [$label, $count, $description, $color]): ?>
        <article class="rounded-2xl p-5 shadow-sm <?= $color ?>"><span class="block text-sm font-bold opacity-70"><?= $label ?></span><strong class="my-1 block text-3xl font-bold"><?= $count ?></strong><small class="text-sm font-semibold opacity-70"><?= $description ?></small></article>
    <?php endforeach; ?>
</section>

<div class="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_19rem]">
    <section class="grid gap-5" aria-label="TODO管理">
        <section class="rounded-2xl border border-stone-200 bg-white/90 p-5 shadow-sm sm:p-7">
            <div class="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p class="mb-1 text-xs font-extrabold tracking-[0.14em] text-emerald-700">TASK COMPOSER</p><h2 class="font-serif text-xl font-bold text-slate-900"><?= $editingTodo === null ? '新しいタスクを追加' : 'タスクを編集' ?></h2></div><?php if ($editingTodo !== null): ?><a class="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-800" href="index.php<?= $returnTag === '' ? '' : '?tag=' . rawurlencode($returnTag) ?>">編集をやめる</a><?php endif; ?></div>
            <form action="index.php" method="post">
                <?= csrfInput() ?><input type="hidden" name="return_tag" value="<?= e($returnTag) ?>"><input type="hidden" name="action" value="<?= $editingTodo === null ? 'add_todo' : 'update_todo' ?>"><?php if ($editingTodo !== null): ?><input type="hidden" name="id" value="<?= (int) $editingTodo['id'] ?>"><?php endif; ?>
                <div class="grid gap-3 md:grid-cols-[minmax(0,1fr)_11rem_auto]">
                    <div><label class="sr-only" for="title">TODO</label><input class="w-full rounded-xl border border-stone-300 bg-white px-3 py-3 text-slate-900 placeholder:text-slate-400 focus:border-emerald-600 focus:outline-2 focus:outline-emerald-200" id="title" name="title" type="text" placeholder="例：企画書の下書きを作成" value="<?= $editingTodo === null ? '' : e((string) $editingTodo['title']) ?>" aria-describedby="title-hint" required autofocus><small class="ml-1 mt-1.5 block text-xs font-medium text-slate-500" id="title-hint">最大100文字</small></div>
                    <div><label class="sr-only" for="tag_ids">タグ</label><select class="min-h-12 w-full rounded-xl border border-stone-300 bg-white px-3 py-2 text-slate-700 focus:border-emerald-600 focus:outline-2 focus:outline-emerald-200" id="tag_ids" name="tag_ids[]" multiple aria-describedby="tag-hint"><?php foreach ($tags as $tag): ?><option value="<?= (int) $tag['id'] ?>" <?= $editingTodo !== null && in_array((int) $tag['id'], $editingTodo['tag_ids'], true) ? 'selected' : '' ?>><?= e((string) $tag['name']) ?></option><?php endforeach; ?></select><small class="ml-1 mt-1.5 block text-xs font-medium text-slate-500" id="tag-hint">複数選択できます</small></div>
                    <button class="self-start rounded-xl bg-emerald-800 px-5 py-3 font-bold text-white transition hover:bg-emerald-950 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-700" type="submit"><?= $editingTodo === null ? '追加' : '保存' ?></button>
                </div>
            </form>
        </section>
        <?php if ($message !== null): ?><p class="rounded-xl border px-4 py-3 text-sm font-bold <?= $message['type'] === 'error' ? 'border-red-200 bg-red-50 text-red-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800' ?>" role="<?= $message['type'] === 'error' ? 'alert' : 'status' ?>"><?= e($message['message']) ?></p><?php endif; ?>
        <section class="rounded-2xl border border-stone-200 bg-white/90 p-5 shadow-sm sm:p-7" aria-label="TODO一覧">
            <div class="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p class="mb-1 text-xs font-extrabold tracking-[0.14em] text-emerald-700">YOUR TASKS</p><h2 class="font-serif text-xl font-bold text-slate-900">タスク一覧</h2></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-sm font-extrabold text-emerald-800"><?= count($todos) ?> 件</span></div>
            <nav class="mb-5 flex flex-wrap gap-2" aria-label="タグで絞り込む"><a class="rounded-full px-3 py-2 text-sm font-bold <?= $selectedTag === null && !$showUntagged ? 'bg-emerald-800 text-white' : 'bg-stone-100 text-slate-600' ?>" href="index.php">すべて</a><?php foreach ($tags as $tag): ?><a class="rounded-full px-3 py-2 text-sm font-bold <?= $selectedTag === (int) $tag['id'] ? 'bg-emerald-800 text-white' : 'bg-stone-100 text-slate-600' ?>" href="index.php?tag=<?= (int) $tag['id'] ?>"><?= e((string) $tag['name']) ?></a><?php endforeach; ?><a class="rounded-full px-3 py-2 text-sm font-bold <?= $showUntagged ? 'bg-emerald-800 text-white' : 'bg-stone-100 text-slate-600' ?>" href="index.php?tag=none">タグなし</a></nav>
            <?php if ($todos === []): ?><div class="rounded-xl border border-dashed border-stone-300 px-5 py-12 text-center text-slate-500"><p class="mb-1 font-bold text-slate-800">表示するTODOはありません。</p><span class="text-sm">上の入力欄から、新しいタスクを追加しましょう。</span></div>
            <?php else: ?><ul class="grid gap-2.5"><?php foreach ($todos as $todo): ?><li class="flex flex-wrap items-center gap-3 rounded-xl border border-stone-200 bg-white p-3 sm:flex-nowrap <?= (int) $todo['is_completed'] === 1 ? 'opacity-65' : '' ?>">
                <form action="index.php" method="post"><?= csrfInput() ?><input type="hidden" name="return_tag" value="<?= e($returnTag) ?>"><input type="hidden" name="action" value="toggle_todo"><input type="hidden" name="id" value="<?= (int) $todo['id'] ?>"><button class="grid size-7 place-items-center rounded-full border-2 <?= (int) $todo['is_completed'] === 1 ? 'border-emerald-800 bg-emerald-800 text-white' : 'border-stone-400 bg-white text-transparent' ?>" type="submit" aria-label="<?= (int) $todo['is_completed'] === 1 ? '未完了に戻す' : '完了にする' ?>">✓</button></form>
                <div class="min-w-0 flex-1"><span class="break-words font-bold <?= (int) $todo['is_completed'] === 1 ? 'text-slate-400 line-through' : 'text-slate-800' ?>"><?= e((string) $todo['title']) ?></span><?php if ($todo['tag_names'] !== null): ?><span class="ml-2 inline-block rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-extrabold text-emerald-800"><?= e((string) $todo['tag_names']) ?></span><?php endif; ?></div>
                <div class="flex w-full gap-1.5 sm:w-auto"><a class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-extrabold text-emerald-800" href="index.php?edit=<?= (int) $todo['id'] ?><?= $returnTag === '' ? '' : '&tag=' . rawurlencode($returnTag) ?>">編集</a><form action="index.php" method="post"><?= csrfInput() ?><input type="hidden" name="return_tag" value="<?= e($returnTag) ?>"><input type="hidden" name="action" value="delete_todo"><input type="hidden" name="id" value="<?= (int) $todo['id'] ?>"><button class="rounded-lg px-2 py-2 text-xs font-extrabold text-red-700 hover:bg-red-50" type="submit">削除</button></form></div>
            </li><?php endforeach; ?></ul><?php endif; ?>
        </section>
    </section>
    <aside class="lg:sticky lg:top-6" aria-label="タグ管理"><section class="rounded-2xl border border-stone-200 bg-white/90 p-5 shadow-sm sm:p-6"><p class="mb-1 text-xs font-extrabold tracking-[0.14em] text-emerald-700">ORGANIZE</p><h2 class="mb-5 font-serif text-xl font-bold text-slate-900">タグを管理</h2>
        <form class="grid grid-cols-[minmax(0,1fr)_auto] gap-2" action="index.php" method="post"><?= csrfInput() ?><input type="hidden" name="return_tag" value="<?= e($returnTag) ?>"><input type="hidden" name="action" value="<?= $editingTag === null ? 'add_tag' : 'update_tag' ?>"><?php if ($editingTag !== null): ?><input type="hidden" name="id" value="<?= (int) $editingTag['id'] ?>"><?php endif; ?><div><label class="sr-only" for="tag_name">タグ名</label><input class="min-w-0 w-full rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-slate-900" id="tag_name" name="name" type="text" placeholder="例：仕事" value="<?= $editingTag === null ? '' : e((string) $editingTag['name']) ?>" aria-describedby="tag-name-hint" required><small class="ml-1 mt-1.5 block text-xs font-medium text-slate-500" id="tag-name-hint">最大30文字</small></div><button class="self-start rounded-xl bg-slate-800 px-4 py-2.5 text-sm font-bold text-white" type="submit"><?= $editingTag === null ? '作成' : '保存' ?></button><?php if ($editingTag !== null): ?><a class="col-span-2 pt-1 text-xs font-bold text-slate-500 underline" href="index.php">キャンセル</a><?php endif; ?></form>
        <ul class="mt-5 grid gap-1"><?php foreach ($tags as $tag): ?><li class="flex items-center gap-2 border-t border-stone-200 py-2.5"><a class="min-w-0 flex-1 break-words text-sm font-extrabold text-slate-800 hover:text-emerald-800" href="index.php?tag=<?= (int) $tag['id'] ?>"><?= e((string) $tag['name']) ?></a><a class="rounded-md bg-emerald-50 px-2 py-1.5 text-xs font-extrabold text-emerald-800" href="index.php?edit_tag=<?= (int) $tag['id'] ?><?= $returnTag === '' ? '' : '&tag=' . rawurlencode($returnTag) ?>">編集</a><form action="index.php" method="post"><?= csrfInput() ?><input type="hidden" name="return_tag" value="<?= e($returnTag) ?>"><input type="hidden" name="action" value="delete_tag"><input type="hidden" name="id" value="<?= (int) $tag['id'] ?>"><button class="rounded-md px-1.5 py-1.5 text-xs font-extrabold text-red-700 hover:bg-red-50" type="submit">削除</button></form></li><?php endforeach; ?></ul>
    </section></aside>
</div>
<?php renderFooter(); ?>
